export const CHANGE_CURRENT_CITY = 'CHANGE_CURRENT_CITY';

export const CHANGE_CITY_NAME = 'CHANGE_CITY_NAME';
export const CHANGE_SUNRISE = 'CHANGE_SUNRISE';
export const CHANGE_SUNSET = 'CHANGE_SUNSET';
export const CHANGE_WEATHER_LIST = 'CHANGE_WEATHER_LIST';

export const CHANGE_FAVORITE_STATE = 'CHANGE_FAVORITE_STATE';
export const ADD_FAVORITE_LIST = 'ADD_FAVORITE_LIST';
export const ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY';
export const REMOVE_FAVORITE_CITY = 'REMOVE_FAVORITE_CITY';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
